# permissions for end users to edit virtualmachinegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: virtualmachine-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinegroup-editor-role
rules:
- apiGroups:
  - vm.example.com
  resources:
  - virtualmachinegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.example.com
  resources:
  - virtualmachinegroups/status
  verbs:
  - get
